import wine from "./img/wine.png";
import flag from "./img/flag.png";

const wines = [
    {   id: 1,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Полусладкое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 1500,
        photo: wine
    },
    {   id: 2,
        name: 'L’ERMITE HERMITAGE 2',
        color: 'Красное',
        sweetness: 'Полусухое',
        grapeSort: 'верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 2500,
        photo: wine
    },
    {   id: 3,
        name: 'L’ERMITE HERMITAGE 3',
        color: 'Розовое',
        sweetness: 'Сухое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 3500,
        photo: wine
    },
    {   id: 4,
        name: 'L’ERMITE HERMITAGE 4',
        color: 'Красное',
        sweetness: 'Сладкое',
        grapeSort: 'Верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 4500,
        photo: wine
    },
    {   id: 5,
        name: 'L’ERMITE HERMITAGE 5',
        color: 'Белое',
        sweetness: 'Полусладкое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 1500,
        photo: wine
    },
    {   id: 6,
        name: 'L’ERMITE HERMITAGE 6',
        color: 'Красное',
        sweetness: 'Полусухое',
        grapeSort: 'верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 2500,
        photo: wine
    },
    {   id: 7,
        name: 'L’ERMITE HERMITAGE 7',
        color: 'Розовое',
        sweetness: 'Сухое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 3500,
        photo: wine
    },
    {   id: 8,
        name: 'L’ERMITE HERMITAGE 8',
        color: 'Красное',
        sweetness: 'Сладкое',
        grapeSort: 'Верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 4500,
        photo: wine
    },
    {   id: 9,
        name: 'L’ERMITE HERMITAGE 9',
        color: 'Красное',
        sweetness: 'Сладкое',
        grapeSort: 'Верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 4500,
        photo: wine
    },
    {   id: 10,
        name: 'L’ERMITE HERMITAGE 10',
        color: 'Белое',
        sweetness: 'Полусладкое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 1500,
        photo: wine
    },
    {   id: 11,
        name: 'L’ERMITE HERMITAGE 11',
        color: 'Красное',
        sweetness: 'Полусухое',
        grapeSort: 'верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 2500,
        photo: wine
    },
    {   id: 12,
        name: 'L’ERMITE HERMITAGE 12',
        color: 'Розовое',
        sweetness: 'Сухое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 3500,
        photo: wine
    },
    {   id: 13,
        name: 'L’ERMITE HERMITAGE 13',
        color: 'Красное',
        sweetness: 'Сладкое',
        grapeSort: 'Верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 4500,
        photo: wine
    },
    {   id: 14,
        name: 'L’ERMITE HERMITAGE 14',
        color: 'Белое',
        sweetness: 'Полусладкое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 1500,
        photo: wine
    },
    {   id: 15,
        name: 'L’ERMITE HERMITAGE 15',
        color: 'Красное',
        sweetness: 'Полусухое',
        grapeSort: 'верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 2500,
        photo: wine
    },
    {   id: 16,
        name: 'L’ERMITE HERMITAGE 16',
        color: 'Розовое',
        sweetness: 'Сухое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 3500,
        photo: wine
    },
    {   id: 17,
        name: 'L’ERMITE HERMITAGE 17',
        color: 'Красное',
        sweetness: 'Сладкое',
        grapeSort: 'Верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 4500,
        photo: wine
    },
    {   id: 18,
        name: 'L’ERMITE HERMITAGE 18',
        color: 'Красное',
        sweetness: 'Сладкое',
        grapeSort: 'Верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 4500,
        photo: wine
    },
]

export default wines;